export enum ActionType {
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOAD_USER = 'LOAD_USER',
  AUTH_ERROR = 'AUTH_ERROR',
  LOGOUT = 'LOGOUT',
}
